# Generated by Django 3.2.11 on 2022-01-16 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_being_edited',
        ),
        migrations.AddField(
            model_name='document',
            name='currently_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_currently_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
