# Generated by Django 3.2.11 on 2022-01-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20220116_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='diff_file',
            field=models.FileField(blank=True, null=True, upload_to='document_diff_files/'),
        ),
    ]
