# Generated by Django 3.2.11 on 2022-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentversion_diff_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='new_document',
            field=models.FileField(blank=True, null=True, upload_to='document_version_files/'),
        ),
    ]
