# Generated by Django 3.2.11 on 2022-01-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentversion_new_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentversion',
            name='new_document',
        ),
        migrations.AddField(
            model_name='documentversion',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document_version_files/'),
        ),
    ]
